//! Coq / Gallina proof emitter.

use crate::ast::{MatchCase, Term, Universe};
use crate::emitter::{EmissionError, ProofEmitter};

/// Proof emitter translating CIC terms and strategies into Coq Gallina code (.v).
#[derive(Debug, Clone, Default)]
pub struct CoqEmitter;

impl CoqEmitter {
    /// Create a new Coq emitter instance.
    pub fn new() -> Self {
        Self
    }

    /// Emit a Coq source file containing a theorem and its exact proof term.
    pub fn emit_source_file(
        &self,
        name: &str,
        ty: &Term,
        proof: &Term,
    ) -> Result<String, EmissionError> {
        let thm = self.emit_theorem(name, ty, proof)?;
        Ok(format!(
            "(* Generated by BourbakiMesh Universal Kernel *)\n\n{}\n",
            thm
        ))
    }
}

impl ProofEmitter for CoqEmitter {
    fn emit_term(&self, term: &Term) -> Result<String, EmissionError> {
        Ok(format_coq_term(term, 0))
    }

    fn emit_theorem(&self, name: &str, ty: &Term, proof: &Term) -> Result<String, EmissionError> {
        let ty_str = self.emit_term(ty)?;
        let proof_str = self.emit_term(proof)?;
        Ok(format!(
            "Theorem {} : {}.\nProof.\n  exact ({}).\nQed.",
            name, ty_str, proof_str
        ))
    }

    fn target_name(&self) -> &'static str {
        "Coq"
    }

    fn file_extension(&self) -> &'static str {
        "v"
    }
}

fn format_coq_universe(u: &Universe) -> String {
    match u {
        Universe::Zero => "Prop".into(),
        Universe::Succ(inner) => {
            if let Universe::Zero = **inner {
                "Set".into()
            } else {
                "Type".into()
            }
        }
        Universe::Param(p) => format!("Type@{{{}}}", p),
    }
}

fn format_coq_case(case: &MatchCase) -> String {
    if case.bindings.is_empty() {
        format!(
            "| {} => {}",
            case.constructor,
            format_coq_term(&case.body, 0)
        )
    } else {
        format!(
            "| {} {} => {}",
            case.constructor,
            case.bindings.join(" "),
            format_coq_term(&case.body, 0)
        )
    }
}

/// Helper formatting terms in Coq Gallina syntax with precedence levels.
/// Precedence levels:
/// 0: Top level (Let, Match, Lam, Pi/forall)
/// 1: Arrow (->)
/// 2: Application (f arg)
/// 3: Atomic (Var, Const, Axiom, Sort, (expr))
fn format_coq_term(term: &Term, prec: u8) -> String {
    match term {
        Term::Sort(u) => format_coq_universe(u),
        Term::Var(name) => name.clone(),
        Term::Const(name, _) => name.clone(),
        Term::Axiom(name) => name.clone(),
        Term::Lam(binder, ty, body) => {
            let res = format!(
                "fun ({} : {}) => {}",
                binder,
                format_coq_term(ty, 0),
                format_coq_term(body, 0)
            );
            if prec > 0 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::Pi(binder, domain, codomain) => {
            let res = if binder == "_" {
                let dom_str = format_coq_term(domain, 2);
                let codom_str = format_coq_term(codomain, 1);
                format!("{} -> {}", dom_str, codom_str)
            } else {
                format!(
                    "forall ({} : {}), {}",
                    binder,
                    format_coq_term(domain, 0),
                    format_coq_term(codomain, 0)
                )
            };
            if prec > 1 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::App(fun, arg) => {
            let fun_str = format_coq_term(fun, 2);
            let arg_str = format_coq_term(arg, 3);
            let res = format!("{} {}", fun_str, arg_str);
            if prec >= 3 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::Let(name, ty, val, body) => {
            let res = format!(
                "let {} : {} := {} in {}",
                name,
                format_coq_term(ty, 0),
                format_coq_term(val, 0),
                format_coq_term(body, 0)
            );
            if prec > 0 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::Match {
            discriminant,
            cases,
            ..
        } => {
            let cases_str = cases
                .iter()
                .map(format_coq_case)
                .collect::<Vec<_>>()
                .join(" ");
            let res = format!(
                "match {} with {} end",
                format_coq_term(discriminant, 0),
                cases_str
            );
            if prec > 0 {
                format!("({})", res)
            } else {
                res
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_coq_emitter_terms() {
        let emitter = CoqEmitter::new();

        // Identity
        let id_term = Term::lam("x", Term::var("A"), Term::var("x"));
        let id_type = Term::arrow(Term::var("A"), Term::var("A"));
        assert_eq!(emitter.emit_term(&id_term).unwrap(), "fun (x : A) => x");
        assert_eq!(emitter.emit_term(&id_type).unwrap(), "A -> A");

        // Universal quantification
        let forall_term = Term::pi(
            "x",
            Term::var("A"),
            Term::app(Term::var("P"), Term::var("x")),
        );
        assert_eq!(
            emitter.emit_term(&forall_term).unwrap(),
            "forall (x : A), P x"
        );

        // Let binding
        let let_term = Term::let_in("h", Term::var("P"), Term::var("p"), Term::var("h"));
        assert_eq!(emitter.emit_term(&let_term).unwrap(), "let h : P := p in h");

        // Complete Theorem
        let thm = emitter
            .emit_theorem("id_proof", &id_type, &id_term)
            .unwrap();
        assert_eq!(
            thm,
            "Theorem id_proof : A -> A.\nProof.\n  exact (fun (x : A) => x).\nQed."
        );
    }
}
