//! Dedukti proof emitter ($\lambda\Pi$-calculus modulo rewriting).

use crate::ast::{MatchCase, Term, Universe};
use crate::emitter::{EmissionError, ProofEmitter};

/// Proof emitter translating CIC terms and strategies into Dedukti (.dk) definitions.
#[derive(Debug, Clone, Default)]
pub struct DeduktiEmitter;

impl DeduktiEmitter {
    /// Create a new Dedukti emitter instance.
    pub fn new() -> Self {
        Self
    }

    /// Emit a Dedukti file header and definitions.
    pub fn emit_file(&self, defs: &[(&str, &Term, &Term)]) -> Result<String, EmissionError> {
        let mut out = "(; Generated by BourbakiMesh Universal Kernel ;)\n\n".to_string();
        for (name, ty, proof) in defs {
            let def_str = self.emit_theorem(name, ty, proof)?;
            out.push_str(&def_str);
            out.push_str("\n\n");
        }
        Ok(out)
    }
}

impl ProofEmitter for DeduktiEmitter {
    fn emit_term(&self, term: &Term) -> Result<String, EmissionError> {
        Ok(format_dedukti_term(term, 0))
    }

    fn emit_theorem(&self, name: &str, ty: &Term, proof: &Term) -> Result<String, EmissionError> {
        let ty_str = self.emit_term(ty)?;
        let proof_str = self.emit_term(proof)?;
        Ok(format!("def {} : {} := {}.", name, ty_str, proof_str))
    }

    fn target_name(&self) -> &'static str {
        "Dedukti"
    }

    fn file_extension(&self) -> &'static str {
        "dk"
    }
}

fn format_dedukti_case(case: &MatchCase) -> String {
    if case.bindings.is_empty() {
        format!(
            "| {} => {}",
            case.constructor,
            format_dedukti_term(&case.body, 0)
        )
    } else {
        format!(
            "| {} {} => {}",
            case.constructor,
            case.bindings.join(" "),
            format_dedukti_term(&case.body, 0)
        )
    }
}

/// Helper formatting terms in Dedukti syntax with precedence.
/// Precedence levels:
/// 0: Top level (Let, Match, Lam, Pi)
/// 1: Arrow (->)
/// 2: Application (f arg)
/// 3: Atomic (Var, Const, Axiom, Sort, (expr))
fn format_dedukti_term(term: &Term, prec: u8) -> String {
    match term {
        Term::Sort(u) => match u {
            Universe::Zero => "Prop".into(),
            _ => "Type".into(),
        },
        Term::Var(name) => name.clone(),
        Term::Const(name, _) => name.clone(),
        Term::Axiom(name) => name.clone(),
        Term::Lam(binder, ty, body) => {
            let res = format!(
                "{} : {} => {}",
                binder,
                format_dedukti_term(ty, 0),
                format_dedukti_term(body, 0)
            );
            format!("({})", res)
        }
        Term::Pi(binder, domain, codomain) => {
            let res = if binder == "_" {
                let dom_str = format_dedukti_term(domain, 2);
                let codom_str = format_dedukti_term(codomain, 1);
                format!("{} -> {}", dom_str, codom_str)
            } else {
                format!(
                    "{} : {} -> {}",
                    binder,
                    format_dedukti_term(domain, 0),
                    format_dedukti_term(codomain, 0)
                )
            };
            if prec > 1 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::App(fun, arg) => {
            let fun_str = format_dedukti_term(fun, 2);
            let arg_str = format_dedukti_term(arg, 3);
            let res = format!("{} {}", fun_str, arg_str);
            if prec >= 3 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::Let(name, ty, val, body) => {
            let res = format!(
                "let {} : {} := {} in {}",
                name,
                format_dedukti_term(ty, 0),
                format_dedukti_term(val, 0),
                format_dedukti_term(body, 0)
            );
            if prec > 0 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::Match {
            discriminant,
            cases,
            ..
        } => {
            let cases_str = cases
                .iter()
                .map(format_dedukti_case)
                .collect::<Vec<_>>()
                .join(" ");
            let res = format!(
                "match {} with {} end",
                format_dedukti_term(discriminant, 0),
                cases_str
            );
            if prec > 0 {
                format!("({})", res)
            } else {
                res
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dedukti_emitter_terms() {
        let emitter = DeduktiEmitter::new();

        // Identity
        let id_term = Term::lam("x", Term::var("A"), Term::var("x"));
        let id_type = Term::arrow(Term::var("A"), Term::var("A"));
        assert_eq!(emitter.emit_term(&id_term).unwrap(), "(x : A => x)");
        assert_eq!(emitter.emit_term(&id_type).unwrap(), "A -> A");

        // Dependent Pi
        let dep_pi = Term::pi(
            "x",
            Term::var("A"),
            Term::app(Term::var("P"), Term::var("x")),
        );
        assert_eq!(emitter.emit_term(&dep_pi).unwrap(), "x : A -> P x");

        // Theorem definition
        let def = emitter.emit_theorem("id_dk", &id_type, &id_term).unwrap();
        assert_eq!(def, "def id_dk : A -> A := (x : A => x).");
    }
}
