//! Isabelle / HOL Isar proof script emitter.

use crate::ast::{MatchCase, Term, Universe};
use crate::emitter::{EmissionError, ProofEmitter};

/// Proof emitter translating CIC terms and strategies into Isabelle/HOL (.thy) theories.
#[derive(Debug, Clone, Default)]
pub struct IsabelleEmitter;

impl IsabelleEmitter {
    /// Create a new Isabelle/HOL emitter.
    pub fn new() -> Self {
        Self
    }

    /// Emit a complete Isabelle/HOL theory containing multiple lemmas.
    pub fn emit_theory(
        &self,
        theory_name: &str,
        lemmas: &[(&str, &Term, &Term)],
    ) -> Result<String, EmissionError> {
        let mut out = format!(
            "(* Generated by BourbakiMesh Universal Kernel *)\ntheory {}\n  imports Main\nbegin\n\n",
            theory_name
        );

        for (name, ty, proof) in lemmas {
            let lemma_str = self.emit_theorem(name, ty, proof)?;
            out.push_str(&lemma_str);
            out.push_str("\n\n");
        }

        out.push_str("end\n");
        Ok(out)
    }
}

impl ProofEmitter for IsabelleEmitter {
    fn emit_term(&self, term: &Term) -> Result<String, EmissionError> {
        Ok(format_isabelle_term(term, 0))
    }

    fn emit_theorem(&self, name: &str, ty: &Term, proof: &Term) -> Result<String, EmissionError> {
        let ty_str = self.emit_term(ty)?;
        let proof_str = self.emit_term(proof)?;
        Ok(format!(
            "lemma {}: \"{}\"\n  proof -\n    show ?thesis using {} by auto\n  qed",
            name, ty_str, proof_str
        ))
    }

    fn target_name(&self) -> &'static str {
        "Isabelle/HOL"
    }

    fn file_extension(&self) -> &'static str {
        "thy"
    }
}

fn format_isabelle_case(case: &MatchCase) -> String {
    if case.bindings.is_empty() {
        format!(
            r"{} \<Rightarrow> {}",
            case.constructor,
            format_isabelle_term(&case.body, 0)
        )
    } else {
        format!(
            r"({} {}) \<Rightarrow> {}",
            case.constructor,
            case.bindings.join(" "),
            format_isabelle_term(&case.body, 0)
        )
    }
}

/// Helper formatting terms in Isabelle/HOL syntax with precedence.
/// Precedence levels:
/// 0: Top level (Let, Case, Lambda, All/Pi)
/// 1: Implication / Arrow (\<longrightarrow>)
/// 2: Function application (f arg)
/// 3: Atomic (Var, Const, Sort, (expr))
fn format_isabelle_term(term: &Term, prec: u8) -> String {
    match term {
        Term::Sort(u) => match u {
            Universe::Zero => "bool".into(),
            _ => "'a".into(),
        },
        Term::Var(name) => name.clone(),
        Term::Const(name, _) => name.clone(),
        Term::Axiom(name) => name.clone(),
        Term::Lam(binder, ty, body) => {
            let res = format!(
                r"(\<lambda> ({} :: {}). {})",
                binder,
                format_isabelle_term(ty, 0),
                format_isabelle_term(body, 0)
            );
            if prec > 0 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::Pi(binder, domain, codomain) => {
            let res = if binder == "_" {
                let dom_str = format_isabelle_term(domain, 2);
                let codom_str = format_isabelle_term(codomain, 1);
                format!(r"{} \<longrightarrow> {}", dom_str, codom_str)
            } else {
                format!(
                    r"\<forall> ({} :: {}). {}",
                    binder,
                    format_isabelle_term(domain, 0),
                    format_isabelle_term(codomain, 0)
                )
            };
            if prec > 1 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::App(fun, arg) => {
            let fun_str = format_isabelle_term(fun, 2);
            let arg_str = format_isabelle_term(arg, 3);
            let res = format!("{} {}", fun_str, arg_str);
            if prec >= 3 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::Let(name, _ty, val, body) => {
            let res = format!(
                "let {} = {} in {}",
                name,
                format_isabelle_term(val, 0),
                format_isabelle_term(body, 0)
            );
            if prec > 0 {
                format!("({})", res)
            } else {
                res
            }
        }
        Term::Match {
            discriminant,
            cases,
            ..
        } => {
            let cases_str = cases
                .iter()
                .map(format_isabelle_case)
                .collect::<Vec<_>>()
                .join(" | ");
            let res = format!(
                "case {} of {}",
                format_isabelle_term(discriminant, 0),
                cases_str
            );
            if prec > 0 {
                format!("({})", res)
            } else {
                res
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_isabelle_emitter_terms() {
        let emitter = IsabelleEmitter::new();

        // Modus Ponens
        let mp_type = Term::arrow(
            Term::var("P"),
            Term::arrow(Term::arrow(Term::var("P"), Term::var("Q")), Term::var("Q")),
        );
        let mp_term = Term::lam(
            "p",
            Term::var("P"),
            Term::lam(
                "f",
                Term::arrow(Term::var("P"), Term::var("Q")),
                Term::app(Term::var("f"), Term::var("p")),
            ),
        );

        let mp_type_str = emitter.emit_term(&mp_type).unwrap();
        assert_eq!(
            mp_type_str,
            r"P \<longrightarrow> (P \<longrightarrow> Q) \<longrightarrow> Q"
        );

        let thm = emitter
            .emit_theorem("mp_lemma", &mp_type, &mp_term)
            .unwrap();
        assert!(thm.contains("lemma mp_lemma:"));
        assert!(thm.contains("proof -"));
        assert!(thm.contains("qed"));
    }
}
