//! Zero-Trust Lean 4 kernel verification bridge and theorem validator.

use crate::ast::Term;
use crate::emitter::ToLean;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Instant;
use thiserror::Error;
use uuid::Uuid;

/// Verification report returned by the reference Lean 4 kernel.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VerificationReport {
    /// True if the proof was successfully type-checked with zero errors.
    pub success: bool,
    /// Name of the certified theorem.
    pub theorem_name: String,
    /// The formatted Lean 4 source code submitted to the kernel.
    pub emitted_code: String,
    /// Raw output / diagnostics emitted by the Lean 4 kernel.
    pub kernel_output: String,
    /// Elaboration and type-checking duration in milliseconds.
    pub elaboration_duration_ms: u64,
}

/// Errors occurring during Lean 4 verification.
#[derive(Debug, Error)]
pub enum VerificationError {
    #[error("IO error interacting with Lean 4 toolchain: {0}")]
    Io(#[from] std::io::Error),

    #[error("Lean 4 kernel rejected proof: {diagnostics}")]
    TypeCheckFailure { diagnostics: String, code: String },

    #[error("Lean toolchain not found on path (lean/lake)")]
    ToolchainNotFound,

    #[error("Verification timed out after {0} seconds")]
    Timeout(u64),
}

/// Lean 4 verification environment bridge executing kernel checks via Lake.
#[derive(Debug, Clone)]
pub struct LeanEnvironment {
    /// Absolute or relative path to the `lean_target` package directory.
    pub lean_target_path: PathBuf,
    /// Optional explicit path to `lake` executable.
    pub lake_binary: Option<PathBuf>,
}

impl LeanEnvironment {
    /// Create a new Lean verification environment targeting a specific Lake workspace.
    pub fn new(lean_target_path: impl Into<PathBuf>) -> Self {
        let path = lean_target_path.into();
        let lake_binary = find_lake_binary();
        Self {
            lean_target_path: path,
            lake_binary,
        }
    }

    /// Automatically discover the workspace `lean_target` directory.
    pub fn default_target() -> Self {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into());
        let possible_paths = [
            PathBuf::from(&manifest_dir).join("../../lean_target"),
            PathBuf::from(&manifest_dir).join("../lean_target"),
            PathBuf::from("lean_target"),
            PathBuf::from("../lean_target"),
        ];

        let target_path = possible_paths
            .into_iter()
            .find(|p| p.exists() && p.join("lakefile.toml").exists())
            .unwrap_or_else(|| PathBuf::from("lean_target"));

        Self::new(target_path)
    }

    /// Generate valid Lean 4 source code for a theorem statement and proof term.
    pub fn generate_lean_module(theorem_name: &str, prop_type: &Term, proof_term: &Term) -> String {
        format!(
            "-- Auto-generated by LEANForward / BourbakiMesh\nimport LeanTarget.Harness\n\ntheorem {} : {} :=\n  {}\n",
            theorem_name,
            prop_type.to_lean_string(),
            proof_term.to_lean_string()
        )
    }

    /// Verify an extracted CIC proof term against a theorem proposition type.
    pub fn verify_term(
        &self,
        theorem_name: &str,
        prop_type: &Term,
        proof_term: &Term,
    ) -> Result<VerificationReport, VerificationError> {
        let code = Self::generate_lean_module(theorem_name, prop_type, proof_term);
        self.verify_raw_lean(theorem_name, &code)
    }

    /// Submit raw Lean 4 code to the reference kernel via `lake env lean`.
    pub fn verify_raw_lean(
        &self,
        module_name: &str,
        lean_code: &str,
    ) -> Result<VerificationReport, VerificationError> {
        let lake_bin = self
            .lake_binary
            .as_ref()
            .cloned()
            .or_else(find_lake_binary)
            .ok_or(VerificationError::ToolchainNotFound)?;

        if !self.lean_target_path.exists() {
            return Err(VerificationError::Io(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                format!(
                    "lean_target directory not found at {:?}",
                    self.lean_target_path
                ),
            )));
        }

        // Create temporary file inside lean_target directory
        let temp_filename = format!("temp_verify_{}.lean", Uuid::new_v4().simple());
        let temp_path = self.lean_target_path.join(&temp_filename);
        fs::write(&temp_path, lean_code)?;

        let start_time = Instant::now();

        // Run `lake env lean <temp_filename>`
        let mut cmd = Command::new(&lake_bin);
        cmd.arg("env")
            .arg("lean")
            .arg(&temp_filename)
            .current_dir(&self.lean_target_path);

        // Inherit or extend PATH with ~/.elan/bin if present
        if let Some(elan_bin) = elan_bin_dir() {
            if let Ok(current_path) = std::env::var("PATH") {
                let extended_path = format!("{}:{}", elan_bin.display(), current_path);
                cmd.env("PATH", extended_path);
            }
        }

        let output = cmd.output();

        // Clean up temp file
        let _ = fs::remove_file(&temp_path);

        let duration_ms = start_time.elapsed().as_millis() as u64;

        let output = output?;
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        let combined_output = format!("{}{}", stdout, stderr).trim().to_string();

        // Check for compilation errors or unverified sorry
        let has_error = !output.status.success()
            || combined_output.contains("error:")
            || combined_output.contains("declaration uses `sorry`")
            || combined_output.contains("declaration uses 'sorry'");

        if has_error {
            return Err(VerificationError::TypeCheckFailure {
                diagnostics: combined_output,
                code: lean_code.to_string(),
            });
        }

        Ok(VerificationReport {
            success: true,
            theorem_name: module_name.into(),
            emitted_code: lean_code.to_string(),
            kernel_output: combined_output,
            elaboration_duration_ms: duration_ms,
        })
    }
}

/// Helper locating the `lake` binary.
fn find_lake_binary() -> Option<PathBuf> {
    // 1. Check if lake is on PATH
    if let Ok(path) = which::which("lake") {
        return Some(path);
    }

    // 2. Check ~/.elan/bin/lake
    if let Some(elan_dir) = elan_bin_dir() {
        let lake = elan_dir.join("lake");
        if lake.exists() {
            return Some(lake);
        }
    }

    // 3. Fallback to common Unix locations
    let standard_locations = ["/usr/local/bin/lake", "/usr/bin/lake"];
    for loc in &standard_locations {
        let p = PathBuf::from(loc);
        if p.exists() {
            return Some(p);
        }
    }

    None
}

/// Helper returning the ~/.elan/bin path if present.
fn elan_bin_dir() -> Option<PathBuf> {
    if let Ok(home) = std::env::var("HOME") {
        let elan_bin = Path::new(&home).join(".elan").join("bin");
        if elan_bin.exists() {
            return Some(elan_bin);
        }
    }
    None
}

mod which {
    use std::path::PathBuf;
    use std::process::Command;

    pub fn which(name: &str) -> Result<PathBuf, std::io::Error> {
        let output = Command::new("which").arg(name).output()?;
        if output.status.success() {
            let path_str = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !path_str.is_empty() {
                return Ok(PathBuf::from(path_str));
            }
        }
        Err(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("Executable {} not found on PATH", name),
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_lean_module() {
        let prop = Term::pi(
            "A",
            Term::prop(),
            Term::arrow(Term::var("A"), Term::var("A")),
        );
        let proof = Term::lam(
            "A",
            Term::prop(),
            Term::lam("h", Term::var("A"), Term::var("h")),
        );
        let code = LeanEnvironment::generate_lean_module("identity_thm", &prop, &proof);
        assert!(code.contains("theorem identity_thm : (A : Prop) -> A -> A :="));
        assert!(code.contains("fun (A : Prop) => fun (h : A) => h"));
    }
}
